### ISSUE TITLE
Object.assign() code example

### ISSUE THREAD

**Issue by jackW50** [learn-co-curriculum/js-data-structures-objects-readme#10]
The return value for wednesdayMenu contains the nested object of the first argument, when I think it should contain the nested object of the last argument.

_Code From My Console_

```js
function createNewMenu (oldMenu, menuChanges) {
    return Object.assign({}, oldMenu, menuChanges);
}
undefined

const tuesdayMenu = {
    cheesePlate: {
        soft: 'Chevre',
        semisoft: 'Gruyere',
        hard: 'Manchego'
    },
    fries: 'Sweet potato',
    salad: 'Caesar'
};
undefined

const newOfferings = { 
    cheesePlate: {
        soft: 'Brie',
        semisoft: 'Fontina'
    },
    salad: 'Southwestern'
};
undefined

const wednesdayMenu = createNewMenu(tuesdayMenu, newOfferings);
undefined

wednesdayMenu;
{cheesePlate: {…}, fries: "Sweet potato", salad: "Southwestern"}
**cheesePlate: {soft: "Brie", semisoft: "Fontina"}**
fries: "Sweet potato"
salad: "Southwestern"
```

```js
function createNewMenu (oldMenu, menuChanges) {
  return Object.assign({}, oldMenu, menuChanges);
}
 
const tuesdayMenu = {
  cheesePlate: {
    soft: 'Chèvre',
    semiSoft: 'Gruyère',
    hard: 'Manchego'
  },
  fries: 'Sweet potato',
  salad: 'Caesar'
};
 
const newOfferings = {
  cheesePlate: {
    soft: 'Brie',
    semiSoft: 'Fontina'
  },
  salad: 'Southwestern'
};
 
const wednesdayMenu = createNewMenu(tuesdayMenu, newOfferings);
 
wednesdayMenu;
// => { cheesePlate: **{ soft: "Brie", semiSoft: "Fontina", hard: "Manchego" }**, fries: "Sweet potato", salad: "Southwestern" }
```

**Comment by jackW50** [comment]
I guess it's not really the first argument's nested object value, but more of a combination of both the first argument and second arguments nested object. From my console and the function that was used, it doesn't seem to merge the two nested objects properties, but just uses the value of the nested object as a whole to overwrite the first argument's nested object value.

**Comment by drakeltheryuujin** [comment]
Hi @jackW50,

I'm having difficulty reproducing the issue that you're having. This issue would be perfect for the [Ask a Question](http://help.learn.co/ask-a-question/where-can-i-ask-a-question-about-a-lesson) (AAQ) feature, where the [Technical Coaches](http://help.learn.co/instructional-support/receiving-course-support/who-are-the-technical-coaches) (on [supported tracks](http://help.learn.co/instructional-support/receiving-course-support/does-my-program-or-course-have-technical-coach-support)) and fellow community members can help you figure it out. For some tips on how to take full advantage of AAQ, check out [this helpful article](http://help.learn.co/ask-a-question/how-to-optimize-time-in-ask-a-question) in the [Learn Help Center](http://help.learn.co/).

If, after consulting the Help Center and AAQ, you still feel that this is an issue with the curriculum itself, please reopen the issue and provide more detail about why it's a curriculum issue, the steps needed to reproduce the issue.

Thanks!

**Comment by jackW50** [comment]
***For This Code Example In The Lesson***
--All I was trying to say was that the return value for wednesdayMenu; is not correct, at least not what I'm getting in my console. ---

function createNewMenu (oldMenu, menuChanges) {
  return Object.assign({}, oldMenu, menuChanges);
}

const tuesdayMenu = {
  cheesePlate: {
    soft: 'Chèvre',
    semiSoft: 'Gruyère',
    hard: 'Manchego'
  },
  fries: 'Sweet potato',
  salad: 'Caesar'
};

const newOfferings = {
  cheesePlate: {
    soft: 'Brie',
    semiSoft: 'Fontina'
  },
  salad: 'Southwestern'
};

const wednesdayMenu = createNewMenu(tuesdayMenu, newOfferings);

wednesdayMenu;
// => { cheesePlate: { soft: "Brie", semiSoft: "Fontina", hard: "Manchego" }, fries: "Sweet potato", salad: "Southwestern" }

tuesdayMenu;
// => { cheesePlate: { soft: "Chèvre", semiSoft: "Gruyère", hard: "Manchego" }, fries: "Sweet potato", salad: "Caesar" }

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
