### ISSUE TITLE
Objects in javascript : object.assign/deep copy - Link does not work!

### ISSUE THREAD

**Issue by sjwakeman** [learn-co-curriculum/js-data-structures-objects-readme#15]
https://medium.com/tkssharma/objects-in-javascript-object-assign-deep-copy-64106c9aefab

ERROR
410
This account is under investigation or was found in violation of the Medium Rules.
There are thousands of stories to read on Medium. Visit our homepage
to find one that’s right for you.
Take me to Medium

**Comment by lizbur10** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved. Note, however, that if you are working in Canvas the changes may not show up right away.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced. 💙
