### ISSUE TITLE
Object assign/Deep copy is broke

### ISSUE THREAD

**Issue by jacquibushfi** [learn-co-curriculum/js-data-structures-objects-readme#16]
https://medium.com/@tkssharma/objects-in-javascript-object-assign-deep-copy-64106c9aefab

**Comment by lizbur10** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved. Note, however, that if you are working in Canvas the changes may not show up right away.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced. 💙
