### ISSUE TITLE
Deleted resource 

### ISSUE THREAD

**Issue by refia-co** [learn-co-curriculum/js-data-structures-objects-readme#18]
Last resource in the lesson is a medium story which is deleted.

**Comment by lizbur10** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved. Note, however, that if you are working in Canvas the changes may not show up right away.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced. 💙
