### ISSUE TITLE
The link at the end of the lesson returns a 410 status error

### ISSUE THREAD

**Issue by charlie763** [learn-co-curriculum/js-data-structures-objects-readme#20]
https://medium.com/@tkssharma/objects-in-javascript-object-assign-deep-copy-64106c9aefab is the link
Objects in javascript : object.assign/deep copy is the title of the link

Looks like the author deleted the medium article.

**Comment by lizbur10** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved. Note, however, that if you are working in Canvas the changes may not show up right away.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced. 💙
