### ISSUE TITLE
Medium Link not working anymore...

### ISSUE THREAD

**Issue by raulsposito** [learn-co-curriculum/js-data-structures-objects-readme#22]
Just a heads up since the article seems to have been removed 👍 

![image](https://user-images.githubusercontent.com/15642008/101230531-9ea30980-3684-11eb-88d9-bbfbc454c6ea.png)

**Comment by lizbur10** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved. Note, however, that if you are working in Canvas the changes may not show up right away.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced. 💙

**Comment by raulsposito** [comment]
Thank you Liz for your kind response! I'm always glad to help around and give back a little to this wonderful community. Thanks also for fixing the link :)
