### ISSUE TITLE
return value incorrect in 'A BRIEF TEASER: ARRAYS AND OBJECTS' section

### ISSUE THREAD

**Issue by gb23** [learn-co-curriculum/js-data-structures-objects-readme#4]
The readme states:
myArray[myArray.length - 1];
// => undefined
However, I have found 
// => 7

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback.

You are correct; the return value is 7. We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
