### ISSUE TITLE
Confusion about what const means for Objects

### ISSUE THREAD

**Issue by Denbox** [learn-co-curriculum/js-data-structures-objects-readme#5]
Maybe I am just missing something, but this behavior is quite confusing to me- from what we have learned so far, const variables are immutable within their scope. I understand that a const object cannot be redeclared, but to new learners this behavior may be unexpected. In my opinion, it seems like some more explanation here would be beneficial! :)

This is the code snippet that I am talking about.

```
function nondestructivelyUpdateObject(obj, key, value) {
  const newObj = { ...obj };
 
  newObj[key] = value;
 
  return newObj;
}
```

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
