### ISSUE TITLE
typo in A BRIEF TEASER: ARRAYS AND OBJECTS

### ISSUE THREAD

**Issue by f3igao** [learn-co-curriculum/js-data-structures-objects-readme#6]
Following code snippet might be a typo:
myArray[myArray.length - 1];
// => undefined

I'm thinking it should be myArray[myArray.length]. myArray[myArray.length -1] returns 7.

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback. 

The expected result should be seven in that exampled. We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
