### ISSUE TITLE
This paragraph is unclear. Please elaborate.

### ISSUE THREAD

**Issue by atxrenegade** [learn-co-curriculum/js-data-structures-objects-readme#8]
A Side Note: You may notice that we're using const here, but adding a key and value. But that can't be right, since const is immutable, right? Well, the const is used to make variables that cannot be re-assigned, but the content is still mutable. Variables in JavaScript can be thought of as 'buckets' containing stuff. You can place data into the container and then refer to it with the variable name. The data in a const is still mutable, but the bucket is not. So declaring an Object, const testObject = {a: 1}, and then trying to reassign it, testObject = {b:2}, will cause an error because we are trying to re-assign the variable testObject to a new Object. Modifying properties, such as adding keys or pushing into an Array, won't re- assign the Object, just change the content.

**Comment by sgharms** [comment]
Thanks, Renegade. We've modified

@sgharms (UT, class of '00)
